bash: add tempshell for experiments with shell env

diff --git a/dot_config/bash/functions b/dot_config/bash/functions
--- a/dot_config/bash/functions
+++ b/dot_config/bash/functions
@@ -178,3 +178,17 @@ function gerrit-latest {
     local refs=$(git ls-remote $(git remote get-url $remote_name) "*/$review_id/*" | awk '/[0-9]+$/ {print $2}')
     [[ -n "$refs" ]] && { sort -rV | head -n 1; } <<<"$refs"
 }
+
+function tempshell {
+    local dir
+    dir=$(mktemp -d --tmpdir "${1:-experiment.XXXXXX}") || {
+        local retval=$?
+        echo "Failed to create temporary directory" 2>&1
+        return $retval
+    }
+    echo "Switched to temp dir: $dir" 2>&1
+    echo "This directory will be deleted when subshell exits." 2>&1
+    ( cd "$dir" || return
+        trap 'rm -rf "$dir" && echo "Cleaned up $dir" 2>&1' INT TERM QUIT EXIT
+        bash --login )
+}
